version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: poolfinder-api
    expose:
      - "8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poolfinder-web
    environment:
      FASTAPI_URL: http://api:8000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy